<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtqkhQF\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtqkhQF/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVtqkhQF.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVtqkhQF\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerVtqkhQF\appAppKernelDevDebugContainer([
    'container.build_hash' => 'VtqkhQF',
    'container.build_id' => 'd3b07b9c',
    'container.build_time' => 1722825376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVtqkhQF');
