<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0LG7NZIBvFgVj/hAlsTX'."\n".'IuS1UcgbytYNNxrn2jUADwGkHEXUy+lmcgV7dWLFiRXek8UwTrNfVcv/63Nyc8Ci'."\n".'g/Q6Z5/pRHR+3LgWVEBDkpq091QWVUmraep1ZMXYbAmwPIf+jfQ4kRwTi/uR5u9G'."\n".'c+MskFObqg21x0Wh/V77HyXnupGlhGcP7ygxuvs2ZXR14QINPt276Nk3pPN1HPAJ'."\n".'N1M7ipyhk+1hQU4UqgHUL+qseYPdgdqdRN2j5Sy2Ib28eNEx39BAf+lzPG1m7+UV'."\n".'Wf59RA8X0HHGsukh6YUoAYSe2+h2hhKSnnoBXWJS5erBEGFcJznGK9PgUaR/f8nx'."\n".'wQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
